name: Build SebaBiblio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (ci)
        run: npm ci --no-audit --prefer-offline

      - name: Ensure electron-builder available
        run: npm install --no-audit --no-fund electron-builder@^26

      - name: Build Electron app (windows)
        # --publish never avoids attempt to upload to Releases
        run: npx electron-builder --win --x64 --publish never

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SebaBiblio_build
          path: dist/**
